import { BRAND } from "./config.js";

export const TOPICS = [
  {
    id: 1, icon: "⚡", cat: "Instalaciones",
    title: "Data Center por dentro",
    color: BRAND.cyan,
    desc: "Tour, componentes, niveles Tier",
    system: "Explica data centers: diseño físico, niveles Tier I-IV, cooling, energía redundante, norma TIA-942. Usa contexto colombiano cuando aplique.",
  },
  {
    id: 2, icon: "☀️", cat: "Solar",
    title: "Energía Solar Empresarial",
    color: BRAND.green,
    desc: "Paneles, inversores, ROI en Colombia",
    system: "Explica energía solar para empresas: dimensionamiento, inversores, baterías, ROI típico en Colombia, incentivos tributarios Ley 1715.",
  },
  {
    id: 3, icon: "🧠", cat: "IA",
    title: "Control por Voz con IA",
    color: BRAND.purple,
    desc: "ESP32, Claude API, GPIO, automatización",
    system: "Explica el pipeline de voz a acción: INMP441 → ESP-SR wake word → Whisper STT → Claude API → GPIO. Tecnología IIT con ESP32-S3.",
  },
  {
    id: 4, icon: "🔌", cat: "Networking",
    title: "Redes Empresariales",
    color: BRAND.cyan,
    desc: "WiFi vs empresarial, switches, VLANs",
    system: "Explica redes empresariales: switches gestionados, VLANs, WiFi 6, segmentación, redundancia. Contrasta con redes domésticas.",
  },
  {
    id: 5, icon: "📡", cat: "IoT",
    title: "IoT Industrial",
    color: BRAND.green,
    desc: "Sensores, MQTT, Node-RED, dashboards",
    system: "Explica IoT industrial: protocolos MQTT/Modbus, sensores, Node-RED, dashboards en tiempo real, casos de uso en LATAM.",
  },
  {
    id: 6, icon: "🤖", cat: "Automatización",
    title: "Automatización con Node-RED",
    color: BRAND.purple,
    desc: "Flujos, integraciones, casos reales",
    system: "Explica Node-RED: flujos visuales, nodos disponibles, integración con APIs, Home Assistant, ESP32 y sistemas industriales.",
  },
  {
    id: 7, icon: "📋", cat: "Normativa",
    title: "RETIE / RETILAP / RITEL",
    color: BRAND.cyan,
    desc: "Reglamentos eléctricos colombianos",
    system: "Explica los reglamentos colombianos: RETIE (instalaciones eléctricas), RETILAP (iluminación), RITEL (telecomunicaciones). Sé preciso y técnico.",
  },
  {
    id: 8, icon: "🛡️", cat: "Seguridad",
    title: "Seguridad en Infraestructura",
    color: BRAND.green,
    desc: "Firewalls, VPN, ZeroTier, acceso remoto",
    system: "Explica seguridad IT: firewalls, VPN site-to-site, ZeroTier overlay, acceso remoto seguro, hardening de servidores Linux.",
  },
  {
    id: 9, icon: "📊", cat: "Monitoreo",
    title: "Monitoreo en Tiempo Real",
    color: BRAND.purple,
    desc: "Home Assistant, dashboards, alertas",
    system: "Explica monitoreo de infraestructura: Home Assistant, Grafana, alertas automáticas, inversores solares Felicity, integración con APIs propietarias.",
  },
  {
    id: 10, icon: "🏗️", cat: "Instalaciones",
    title: "Cableado Estructurado",
    color: BRAND.cyan,
    desc: "Normas TIA-942, racks, patch panels",
    system: "Explica cableado estructurado: normas TIA-568/942, categorías de cable, organización de racks, patch panels, etiquetado profesional.",
  },
  {
    id: 11, icon: "💰", cat: "Negocio",
    title: "Costos y ROI en Colombia",
    color: BRAND.green,
    desc: "Inversión, ahorro energético, precios 2026",
    system: "Explica costos de infraestructura IT en Colombia 2026: rangos de precios por proyecto, cálculo de ROI, ahorro energético, financiamiento.",
  },
  {
    id: 12, icon: "🌐", cat: "Conectividad",
    title: "Conectividad en Bogotá",
    color: BRAND.purple,
    desc: "ISP, fibra, redundancia, 2.600 msnm",
    system: "Explica conectividad empresarial en Bogotá: ISPs disponibles, fibra óptica, redundancia de enlaces, consideraciones a 2.600 msnm.",
  },
  {
    id: 13, icon: "🔋", cat: "Solar",
    title: "UPS y Respaldo Eléctrico",
    color: BRAND.cyan,
    desc: "Baterías, inversores Felicity, autonomía",
    system: "Explica sistemas UPS y respaldo: tipos de UPS, inversores Felicity Solar, bancos de baterías, cálculo de autonomía, transferencia automática.",
  },
  {
    id: 14, icon: "🎙️", cat: "IA",
    title: "Whisper STT + Claude",
    color: BRAND.green,
    desc: "Pipeline de voz a acción GPIO",
    system: "Explica el pipeline de reconocimiento de voz: OpenAI Whisper API, procesamiento de audio INMP441, integración Claude API, latencia y optimización.",
  },
  {
    id: 15, icon: "📱", cat: "IoT",
    title: "ESP32 y Microcontroladores",
    color: BRAND.purple,
    desc: "Firmware, WebSocket, web embebida",
    system: "Explica el ecosistema ESP32: variantes (S3, C3, original), Arduino vs ESP-IDF, WebSocket, web embebida, OTA, GPIO y periféricos.",
  },
  {
    id: 16, icon: "☁️", cat: "Cloud",
    title: "On-premise vs Cloud",
    color: BRAND.cyan,
    desc: "Cuándo conviene cada opción en LATAM",
    system: "Compara on-premise vs cloud para empresas colombianas: costos reales, latencia, soberanía de datos, casos donde conviene cada opción.",
  },
  {
    id: 17, icon: "🏭", cat: "Casos",
    title: "Casos de Éxito IIT",
    color: BRAND.green,
    desc: "Proyectos ejecutados en Colombia",
    system: "Describe casos de éxito típicos de IIT: instalaciones de data centers, redes empresariales, energía solar y automatización en Colombia.",
  },
  {
    id: 18, icon: "⚙️", cat: "Integración",
    title: "Integración de Sistemas",
    color: BRAND.purple,
    desc: "APIs, protocolos, interoperabilidad",
    system: "Explica integración de sistemas: REST APIs, WebSocket, MQTT, Modbus, protocolos industriales, middleware y orquestación de servicios.",
  },
  {
    id: 19, icon: "🧩", cat: "IA",
    title: "RAG y Chatbots Técnicos",
    color: BRAND.cyan,
    desc: "Embeddings, vector store, consultas RETIE",
    system: "Explica RAG (Retrieval Augmented Generation): embeddings, vector stores, pipeline de consulta, aplicación en documentos técnicos como RETIE.",
  },
  {
    id: 20, icon: "🚀", cat: "IIT",
    title: "Historia y Visión IIT",
    color: BRAND.green,
    desc: "De electrónica universitaria a IA industrial",
    system: "Cuenta la historia de InfraestructuraIT: origen en electrónica y sistemas embebidos, evolución hacia data centers, IoT, solar y ahora IA industrial en Colombia.",
  },
];

export const CATEGORIES = ["Todos", ...new Set(TOPICS.map((t) => t.cat))];
